version: "2"

services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    # Modifica el nombre de paquito por tu cuenta de dockerhub
    image: paquito/yo:ej2
    ports:
      - "0.0.0.0:9000:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./html/index.html:/usr/share/nginx/html/index.html
