version: "2"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    # Modifica el nombre de paquito por tu cuenta de dockerhub
    image: paquito/yo:ej3
    ports:
      - "0.0.0.0:80:8000"
    volumes:
      - ./html/index.html:/usr/share/app/html/index.html
      - ./top_secret:/usr/share/app/html/top_secret
